### ISSUE TITLE
LauncherActivity crash - No definition found for FirebaseInstanceId

### ISSUE THREAD

**Issue by AdamSHurwitz** [blockchain/My-Wallet-V3-Android#1261]
# Expect
Run the Blockchain Android app from the _master_ branch. 

# Observe

The app is unable to build.

**8/4/20 Pull Request Build Error**

> No matching client found for package name 'piuk.blockchain.android.dev'

Resolved by refactoring the _google-services.json_ file `package_name` from `"piuk.blockchain.android"` to the current build variant's package name `piuk.blockchain.android.dev`. The 8/3/20 error still persists.

**8/3/20 Runtime Error**
The app opens the _LauncherActivity_ and immediately crashes.

> Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'com.google.firebase.iid.FirebaseInstanceId'. Check your definitions!

Potentially this is due to an issue with the mock _google-services.json_, generated from the quickstart script. It seems to be missing the `api_key` `current_key` value which could explain the FirebaseId issue. There is also a [build error] reported with the current merge as well which could be related.

_Blockchain > app > src > env > google-services.json_

```json
{
  "project_info": {
    "project_number": "623252783566",
    "firebase_url": "https://blockchaintest-ecd1c.firebaseio.com",
    "project_id": "blockchaintest-ecd1c",
    "storage_bucket": "blockchaintest-ecd1c.appspot.com"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:623252783566:android:02baff6e6c46ed96232b9f",
        "android_client_info": {
          "package_name": "piuk.blockchain.android"
        }
      },
      "oauth_client": [
        {
          "client_id": "623252783566-o6j47jlpan97fnibnr0vosvc4lh71sm1.apps.googleusercontent.com",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": "INSERT KEY HERE"
        }
      ],
      "services": {
        "appinvite_service": {
          "other_platform_oauth_client": [
            {
              "client_id": "623252783566-o6j47jlpan97fnibnr0vosvc4lh71sm1.apps.googleusercontent.com",
              "client_type": 3
            }
          ]
        }
      }
    }
  ],
  "configuration_version": "1"
}
{
  "project_info": {
    "project_number": "623252783566",
    "firebase_url": "https://blockchaintest-ecd1c.firebaseio.com",
    "project_id": "blockchaintest-ecd1c",
    "storage_bucket": "blockchaintest-ecd1c.appspot.com"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:623252783566:android:02baff6e6c46ed96232b9f",
        "android_client_info": {
          "package_name": "piuk.blockchain.android"
        }
      },
      "oauth_client": [
        {
          "client_id": "623252783566-o6j47jlpan97fnibnr0vosvc4lh71sm1.apps.googleusercontent.com",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": "INSERT KEY HERE"
        }
      ],
      "services": {
        "appinvite_service": {
          "other_platform_oauth_client": [
            {
              "client_id": "623252783566-o6j47jlpan97fnibnr0vosvc4lh71sm1.apps.googleusercontent.com",
              "client_type": 3
            }
          ]
        }
      }
    }
  ],
  "configuration_version": "1"
}
```

# Setup

1. Import from the GitHub repository.
2. Run the quickstart script from the Android Studio terminal: `./scripts/quick_start.sh`
3. _Build_ > _Make Project_
4. Module Build Variants
- _app:_ `envDevDebug`
- Everything else: `debug`
5. Branch: _origin/master_
6. Devices 
- Google Pixel 1: Android version 10
- Google Pixel 3a emulator: Android version 10, API 29

# Attempt Solutions

1. Try build variants for _app_ module 
   a. _envProdDebug_ - The app runs and crashes immediately throwing the runtime error described above.
   b.  _envStagingDebug_ - After adjusting the _google-services.json_ `package_name` to append `.staging`, the app runs and crashes immediately throwing the runtime error described above. 
   c.  _envTestnetDebug_ - Error: _"e: /Users/adamhurwitz/Code/Android/Blockchain/app/src/main/java/com/blockchain/koin/modules/apiInterceptorsModule.kt: (17, 77): Unresolved reference: VERSION_NAME_SUFFIX"_
   d. _envDevRelease_
3. _File_ > _Invalidate Caches / Restart ..._
4. Check for Android Studio updates: _Android Studio_ > _Check for updates_
> Android Studio 4.0.1
Build #AI-193.6911.18.40.6626763, built on June 24, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: org.jetbrains.kotlin, cn.wjdghd.unique.plugin.id, com.android.tool.sizereduction.plugin, com.developerphil.adbidea, com.google.services.firebase, com.thoughtworks.gauge, mobi.hsz.idea.gitignore

# Full 8/3/20 Runtime Error Log

>2020-08-03 22:55:47.754 15660-15660/? E/ckchain.androi: Unknown bits set in runtime_flags: 0x8000
2020-08-03 22:55:49.852 15660-15660/piuk.blockchain.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: piuk.blockchain.android, PID: 15660
    java.lang.RuntimeException: Unable to start activity ComponentInfo{piuk.blockchain.android/piuk.blockchain.android.ui.launcher.LauncherActivity}: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'piuk.blockchain.android.ui.launcher.LauncherPresenter',scope:Payload]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'piuk.blockchain.android.ui.launcher.LauncherPresenter',scope:Payload]
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:59)
        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:36)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:87)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:214)
        at org.koin.core.scope.Scope.get(Scope.kt:181)
        at piuk.blockchain.android.ui.launcher.LauncherActivity$$special$$inlined$scopedInject$1.invoke(Scope.kt:397)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at piuk.blockchain.android.ui.launcher.LauncherActivity.getLauncherPresenter(Unknown Source:7)
        at piuk.blockchain.android.ui.launcher.LauncherActivity.createPresenter(LauncherActivity.kt:49)
        at piuk.blockchain.android.ui.launcher.LauncherActivity.createPresenter(LauncherActivity.kt:29)
        at piuk.blockchain.androidcoreui.ui.base.BaseMvpActivity.onCreate(BaseMvpActivity.java:22)
        at piuk.blockchain.android.ui.launcher.LauncherActivity.onCreate(LauncherActivity.kt:35)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Single:'com.blockchain.notifications.NotificationTokenManager',scope:Payload]
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:59)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:40)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:48)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:87)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:214)
        at org.koin.core.scope.Scope.get(Scope.kt:181)
        at com.blockchain.koin.modules.ApplicationModuleKt$applicationModule$1$8$71.invoke(applicationModule.kt:1013)
        at com.blockchain.koin.modules.ApplicationModuleKt$applicationModule$1$8$71.invoke(Unknown Source:4)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:36) 
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:87) 
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:214) 
        at org.koin.core.scope.Scope.get(Scope.kt:181) 
        at piuk.blockchain.android.ui.launcher.LauncherActivity$$special$$inlined$scopedInject$1.invoke(Scope.kt:397) 
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81) 
        at piuk.blockchain.android.ui.launcher.LauncherActivity.getLauncherPresenter(Unknown Source:7) 
        at piuk.blockchain.android.ui.launcher.LauncherActivity.createPresenter(LauncherActivity.kt:49) 
        at piuk.blockchain.android.ui.launcher.LauncherActivity.createPresenter(LauncherActivity.kt:29) 
        at piuk.blockchain.androidcoreui.ui.base.BaseMvpActivity.onCreate(BaseMvpActivity.java:22) 
        at piuk.blockchain.android.ui.launcher.LauncherActivity.onCreate(LauncherActivity.kt:35) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'com.google.firebase.iid.FirebaseInstanceId'. Check your definitions!
        at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:247)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:216)
        at org.koin.core.scope.Scope.get(Scope.kt:181)
2020-08-03 22:55:49.852 15660-15660/piuk.blockchain.android E/AndroidRuntime:     at com.blockchain.notifications.koin.NotificationModuleKt$notificationModule$1$1$1.invoke(notificationModule.kt:62)
        at com.blockchain.notifications.koin.NotificationModuleKt$notificationModule$1$1$1.invoke(Unknown Source:4)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
        	... 34 more
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler: java.lang.RuntimeException: Unable to start activity ComponentInfo{piuk.blockchain.android/piuk.blockchain.android.ui.launcher.LauncherActivity}: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'piuk.blockchain.android.ui.launcher.LauncherPresenter',scope:Payload]
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at android.os.Handler.dispatchMessage(Handler.java:107)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at android.os.Looper.loop(Looper.java:214)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at android.app.ActivityThread.main(ActivityThread.java:7356)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at java.lang.reflect.Method.invoke(Native Method)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler: Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'piuk.blockchain.android.ui.launcher.LauncherPresenter',scope:Payload]
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:59)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:36)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:87)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at org.koin.core.scope.Scope.resolveInstance(Scope.kt:214)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at org.koin.core.scope.Scope.get(Scope.kt:181)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at piuk.blockchain.android.ui.launcher.LauncherActivity$$special$$inlined$scopedInject$1.invoke(Scope.kt:397)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at piuk.blockchain.android.ui.launcher.LauncherActivity.getLauncherPresenter(Unknown Source:7)
2020-08-03 22:55:49.854 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at piuk.blockchain.android.ui.launcher.LauncherActivity.createPresenter(LauncherActivity.kt:49)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at piuk.blockchain.android.ui.launcher.LauncherActivity.createPresenter(LauncherActivity.kt:29)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at piuk.blockchain.androidcoreui.ui.base.BaseMvpActivity.onCreate(BaseMvpActivity.java:22)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at piuk.blockchain.android.ui.launcher.LauncherActivity.onCreate(LauncherActivity.kt:35)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at android.app.Activity.performCreate(Activity.java:7802)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at android.app.Activity.performCreate(Activity.java:7791)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler: 	... 11 more
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler: Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Single:'com.blockchain.notifications.NotificationTokenManager',scope:Payload]
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:59)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:40)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:48)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:87)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at org.koin.core.scope.Scope.resolveInstance(Scope.kt:214)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at org.koin.core.scope.Scope.get(Scope.kt:181)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at com.blockchain.koin.modules.ApplicationModuleKt$applicationModule$1$8$71.invoke(applicationModule.kt:1013)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at com.blockchain.koin.modules.ApplicationModuleKt$applicationModule$1$8$71.invoke(Unknown Source:4)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler: 	... 26 more
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler: Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'com.google.firebase.iid.FirebaseInstanceId'. Check your definitions!
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:247)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at org.koin.core.scope.Scope.resolveInstance(Scope.kt:216)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at org.koin.core.scope.Scope.get(Scope.kt:181)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at com.blockchain.notifications.koin.NotificationModuleKt$notificationModule$1$1$1.invoke(notificationModule.kt:62)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at com.blockchain.notifications.koin.NotificationModuleKt$notificationModule$1$1$1.invoke(Unknown Source:4)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler:     at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
2020-08-03 22:55:49.855 15660-15660/piuk.blockchain.android E/UncaughtExceptionHandler: 	... 34 more
2020-08-03 22:55:49.858 15660-15712/piuk.blockchain.android E/FirebaseCrashlytics: Tried to write a fatal exception while no session was open.
2020-08-03 22:55:49.884 688-688/? E/lowmemorykiller: Error writing /proc/15660/oom_score_adj; errno=22

[build error]: https://circleci.com/gh/blockchain/My-Wallet-V3-Android/tree/master

**Comment by AdamSHurwitz** [comment]
The latest commits have been pulled this morning and a new error shows during the _Build > Make Project_ process.

> No matching client found for package name 'piuk.blockchain.android.dev'

**Comment by AdamSHurwitz** [comment]
# Change Build Variant and Package Name

1. Build Variant
   a. _app_: `envStagingDebug`
   b. All other modules: `debug`

**Comment by dserrano-bc** [comment]
thanks for this @AdamSHurwitz , it will be fixed in an upcoming release

**Comment by AdamSHurwitz** [comment]
Thanks @dserrano-bc! I've created a pull request #1263  to update the documentation as well for users to create their own _google-services.json_.
