### ISSUE TITLE
A random crash occured

### ISSUE THREAD

**Issue by avoloshko** [blockchain/My-Wallet-V3-Android#224]
MonetaryUtil takes null context and crashes immediately. The case happens when a fragment is detached and getActivity() returns null.

Call stack:
05-11 14:30:32.596 17615-20595/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                   Process: piuk.blockchain.android, PID: 17615
                                                   java.lang.RuntimeException: An error occured while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
                                                       at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:374)
                                                       at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:369)
                                                       at info.blockchain.wallet.util.PrefsUtil.getValue(PrefsUtil.java:40)
                                                       at info.blockchain.wallet.util.MonetaryUtil.getUndenominatedAmount(MonetaryUtil.java:123)
                                                       at info.blockchain.wallet.SendFragment.getLongValue(SendFragment.java:2028)
                                                       at info.blockchain.wallet.SendFragment.getSpendAmount(SendFragment.java:1073)
                                                       at info.blockchain.wallet.SendFragment.getCoins(SendFragment.java:1089)
                                                       at info.blockchain.wallet.SendFragment.access$300(SendFragment.java:98)
                                                       at info.blockchain.wallet.SendFragment$7.doInBackground(SendFragment.java:423)
                                                       at info.blockchain.wallet.SendFragment$7.doInBackground(SendFragment.java:413)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                       at java.lang.Thread.run(Thread.java:818) 

Fix:
[0001-Fixed-a-crash-when-MonetaryUtil-is-used-when-in-deta.patch.zip](https://github.com/blockchain/My-Wallet-V3-Android/files/259242/0001-Fixed-a-crash-when-MonetaryUtil-is-used-when-in-deta.patch.zip)

**Comment by riaanjvos** [comment]
@avoloshko Thanks for letting us know about this bug. I've started looking into this and the fix should follow shortly.
